Dev
sebasttiano/Owl pull request #1
Opened 2024-07-11 11:06 UTC by sebasttiano

2024-07-11 11:08 UTC, sebasttiano commented
Еще в процессе тесты...

2024-07-11 19:21 UTC, Bazys requested changes
твои же тесты не проходят

# github.com/sebasttiano/Owl/internal/handlers
internal/handlers/interceptors.go:108:15: google.golang.org/grpc/status.Errorf does not support error-wrapping directive %w
FAIL    github.com/sebasttiano/Owl/internal/handlers [build failed]

2024-07-21 10:12 UTC, Bazys requested changes
есть пара вопросов

2024-07-21 10:12 UTC, Bazys commented on internal/cli/form.go
> +			tea.Quit()
эта функция ничего не делает, зачем она?

2024-07-21 10:12 UTC, Bazys commented on internal/cli/form.go
> +			tea.Quit()
и выхода нет из функции

2024-07-21 10:12 UTC, Bazys commented on internal/cli/error.go
> +type ErrorModel struct {
ошибки  такого типа именуются как `XxxError`

https://go.dev/wiki/Errors#naming

2024-07-21 10:12 UTC, Bazys commented on internal/cli/form.go
> +	ctx           context.Context
Использование `context.Context` внутри структуры или в качестве поля в структуре, как правило, не рекомендуется в Go по нескольким причинам. Чтобы понять, почему это происходит, необходимо немного рассказать о том, что такое `context.Context` и как он должен использоваться.  
  
### Что такое `context.Context`?  
  
`context.Context` - это тип в стандартной библиотеке Go, который обеспечивает передачу дедлайнов, сигналов отмены и других значений, связанных с запросами, между различными интерфейсами API и процессами. Он часто передается в качестве первого аргумента функциям и методам, которые выполняют сетевые вызовы, запросы к базам данных или иным образом должны обрабатывать отмены и тайм-ауты.  
  
### Почему встраивание `context.Context` в структуру является плохой практикой  
  
1. **Управление жизненным циклом**: `context.Context` предназначен для создания и передачи по стеку вызовов. Он привязан к жизненному циклу запроса или операции. Встраивание его в структуру может сделать управление жизненным циклом контекста неясным, поскольку структуры часто имеют иной жизненный цикл, чем отдельный запрос или операция.  
  
2. **Изменяемость**: Контекст `context.Context` должен быть неизменяемым; после создания он не должен быть изменен. Размещение его в структуре подразумевает, что он может быть изменен, поскольку поля структуры, как правило, являются изменяемыми.  
  
3. **Антипаттерн**: В Go принято передавать контекст в качестве первого аргумента функции, а не хранить его. Таким образом, область применения и назначение контекста становятся ясными. Встраивая его в структуру, вы скрываете его использование и делаете код менее читабельным и идиоматичным.  
  
4. **Проблемы параллелизма**: Контексты безопасны для использования несколькими горутинами одновременно. Если контекст встраивается в структуру, которая является общей для всех горутин, то это может привести к некорректному использованию, если контекст будет отменен или его значения будут изменены одновременно.  
  
5. **Тестирование и сопровождение**: Тестирование функций, использующих контекст, переданный в качестве аргумента, не вызывает затруднений. Вы можете предоставить контекст, специально предназначенный для тестового сценария. Если же контекст встроен в структуру, то, возможно, придется инстанцировать или имитировать всю структуру, что может оказаться громоздким и хрупким.  
  
6. **Dependency Injection**: Встраивание контекста в структуру препятствует возможности использования DI для передачи контекстов, что может усложнить тестирование и многократное использование компонентов.  
  
7. **Документация и четкость**: Когда контекст передается в качестве аргумента, понятно, что работа функции может знать об отмене, сроках и т.д. При встраивании семантика становится менее ясной, и разработчику сложнее понять предполагаемое поведение, просто взглянув на сигнатуру функции.  
  
### Лучшие практики  
  
- Всегда передавайте `context.Context` в качестве первого параметра функции или метода, если функция/метод этого требует.  
- Не храните `context.Context` в структуре; вместо этого передавайте его явно там, где это необходимо.  
- Используйте значения контекста только для данных, скопированных на запрос, которые передаются через процессы и API, а не для передачи необязательных параметров в функции.  
  
### Обучение концепции  
  
При обучении концепции `context.Context` важно начать с ее предполагаемого использования и того, как она согласуется с философией явности и читабельности Go. Покажите примеры правильного использования контекста и сравните их с примерами, в которых контекст встроен в структуру. Обсудите практические последствия, особенно в части параллелизма и проектирования API. Поощряйте студентов следовать установленным шаблонам Go и обращаться к стандартной библиотеке Go за примерами идиоматического использования.  

Ссылки:

- [https://go.dev/blog/context-and-structs](https://go.dev/blog/context-and-structs)
- [https://golangbyexample.com/using-context-in-golang-complete-guide](https://golangbyexample.com/using-context-in-golang-complete-guide)
- [Golang context best practices](https://www.golangprograms.com/golang-context-best-practices.html#:~:text=There%20are%20several%20best%20practices,network%20requests%20or%20database%20queries)

2024-07-21 10:12 UTC, Bazys commented on internal/cli/form.go
> +	index         int
зачем зто поле?

2024-07-21 10:12 UTC, Bazys commented on internal/cli/column.go
> +func (c *column) setSize(width, height int) {
Параметр функции, названный `height`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `height` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-07-21 10:12 UTC, Bazys commented on internal/handlers/resource.go
> +	userId, err := getUserIDFromContext(ctx)
userID

2024-07-21 10:12 UTC, Bazys commented on internal/server/grpc_server.go
> +	"context"
импорты не отсортированы

2024-07-21 10:12 UTC, Bazys commented on internal/cli/keys.go
> +func (k keyMap) ShortHelp() []key.Binding {
keyMap - лучше сделать ссылочного типа. 
да и в принципе, старайся делать все ссылочного типа, особенного для больших структур

2024-07-23 10:59 UTC, sebasttiano commented on internal/cli/form.go
> +			tea.Quit()
Не заметил, нужно было еще return поставить перед.
Заменил на не просто выход, а еще отобразить сообщение о ошибке в TUI.

2024-07-23 11:01 UTC, sebasttiano commented on internal/cli/form.go
> +			tea.Quit()
Решение выше.

2024-07-23 11:03 UTC, sebasttiano commented on internal/cli/error.go
> +type ErrorModel struct {
Поправил на ModelError

2024-07-23 11:19 UTC, sebasttiano commented on internal/cli/form.go
> +	index         int
Скопипастил с дргуой модельки случайно. Удалил.

2024-07-23 11:21 UTC, sebasttiano commented on internal/cli/column.go
> +func (c *column) setSize(width, height int) {
Удалил

2024-07-23 11:24 UTC, sebasttiano commented on internal/handlers/resource.go
> +	userId, err := getUserIDFromContext(ctx)
Везде переименовал

2024-07-23 11:31 UTC, sebasttiano commented on internal/server/grpc_server.go
> +	"context"
прошелся goimports везде.

2024-07-23 12:31 UTC, sebasttiano commented on internal/cli/keys.go
> +func (k keyMap) ShortHelp() []key.Binding {
сделал

2024-07-23 13:01 UTC, sebasttiano commented on internal/cli/form.go
> +	ctx           context.Context
Везде удалил из структурок.

2024-07-25 12:32 UTC, Bazys requested changes
продолжаем улучшать

2024-07-25 12:32 UTC, Bazys commented on internal/cli/form.go
> +			return fmt.Errorf("EXP is invalid")
ты ничего не подставляешь - модно просто `errors.New()`

2024-07-25 12:32 UTC, Bazys commented on internal/models/models.go
> +		Description string
тут нет тэга json - при маршалинге можешь получит не то что ожидаешь

2024-07-25 12:32 UTC, Bazys commented on internal/cli/form.go
> +	m.ccn.CharLimit = 16 + 3
магические цифры в коде
вынеси в константы - дай понятные названия

2024-07-25 12:32 UTC, Bazys commented on internal/server/tls.go
> +func loadTLSCredentials(certFile, keyFile string) (credentials.TransportCredentials, error) {
возврщать интерфейс не принято в ГО

2024-07-25 12:32 UTC, Bazys commented on internal/cli/cli.go
> +	name, pass, err := c.GetUserCreds(ctx, tlsCredentials)
а тут ошибку проверить?

2024-07-25 12:32 UTC, Bazys commented on internal/cli/authentification.go
> +	cli           *CLI
опять скопипастил из другой модельки?

2024-07-25 12:32 UTC, Bazys commented on internal/service/binary.go
> +func (b *BinaryService) SetBinary(ctx context.Context, data models.Resource) error {
Параметр функции, названный `ctx`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `ctx` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-07-25 12:32 UTC, Bazys commented on internal/cli/authentification.go
> +func (s signInModel) Init() tea.Cmd {
опять не ссылочный тип? 
структурв то не маленькая.

2024-07-27 09:48 UTC, sebasttiano commented on internal/cli/form.go
> +			return fmt.Errorf("EXP is invalid")
поменял

2024-07-27 09:48 UTC, sebasttiano commented on internal/models/models.go
> +		Description string
добавил

2024-07-27 10:04 UTC, sebasttiano commented on internal/cli/form.go
> +	m.ccn.CharLimit = 16 + 3
вынес все подобные в const

2024-07-27 10:23 UTC, sebasttiano commented on internal/server/tls.go
> +func loadTLSCredentials(certFile, keyFile string) (credentials.TransportCredentials, error) {
Тогда я не понимаю, как переделать сигнатуру... Данный интерфейс возвращает ф-ция "func NewTLS(c *tls.Config) TransportCredentials" из пакета "google.golang.org/grpc/credentials" 
Структура tlsCreds, которая имплементирует данный интерфейс и  которая возвращается на самом деле - неимпортируемая и тоже не могу ее указать.

2024-07-27 11:21 UTC, sebasttiano commented on internal/cli/cli.go
> +	name, pass, err := c.GetUserCreds(ctx, tlsCredentials)
Изменил на нормальную обработку ошибок, учитывающую отмену пользователем.

2024-07-27 11:25 UTC, sebasttiano commented on internal/cli/authentification.go
> +	cli           *CLI
Использовал до этого, не почистил... убрал.

2024-07-27 12:27 UTC, sebasttiano commented on internal/service/binary.go
> +func (b *BinaryService) SetBinary(ctx context.Context, data models.Resource) error {
поправил

2024-07-28 07:34 UTC, Bazys approved these changes
Понятно, что улучшать можно бесконечно, но на текущий момент критических вопросов нет

2024-07-28 19:12 UTC, merged